### ISSUE TITLE
Error while trying to download a channel

### ISSUE THREAD

**Issue by Honza572** [Tyrrrz/YoutubeDownloader#412] opened 2024-01-18 16:34 UTC
### Version

1.10.10

### Platform

Windows 11

### Steps to reproduce

URL: https://www.youtube.com/@1AAuto
settings: everything on (https://i.imgur.com/p9QbYL3.png)
Error: https://i.imgur.com/QuPc1Qo.png (sorry it won't let me copy it)
steps: just paste it in
one interesting thing: it happens immidiatelly after I press enter, with previous errors there was a delay

![image](https://github.com/Tyrrrz/YoutubeDownloader/assets/102232480/473b07a5-88ec-4c1e-93b0-c4b330019015)
![image](https://github.com/Tyrrrz/YoutubeDownloader/assets/102232480/501b5f49-1364-4ce2-9962-5c846a91f3ae)

### Details

Expected behavior: working
Actual behavior: throwing error 
(idk what to write here😅😂)

### Checklist

- [X] I have looked through existing issues to make sure that this bug has not been reported before
- [X] I have provided a descriptive title for this issue
- [X] I have made sure that this bug is reproducible on the latest version of the application
- [X] I have provided all the information needed to reproduce this bug as efficiently as possible
- [ ] I have sponsored this project

**Comment by Honza572** [comment] 2024-01-18 16:39
I downloaded latest version again and the same thing happened, Cl build or what is it didn't work either.
Also single video download doesn't work.

**Comment by Tyrrrz** [comment] 2024-01-18 17:02
Duplicate of #411

**Closed as completed by Tyrrrz** 2024-01-18 17:02 UTC
Labels: duplicate
