### ISSUE TITLE
App crashes for Video unavailable in Your Country

### ISSUE THREAD

**Issue by xamarin-enthusiast** [Tyrrrz/YoutubeDownloader#24] opened 2019-06-10 21:54 UTC
The app simply **CRASHES** by encountering a video that is unavailable on YouTube. The URL is valid but "**The uploader has not made this video available in your country.**"

Try this one for example:
https://www.youtube.com/watch?v=7o_rwJwqkDc

This is similar to issue #21.

Need better error trapping.

![image](https://user-images.githubusercontent.com/22284653/59229157-a9700180-8ba7-11e9-99ad-a55be105bdf5.png)

![image](https://user-images.githubusercontent.com/22284653/59229396-47fc6280-8ba8-11e9-8c32-20616a0298d8.png)

![image](https://user-images.githubusercontent.com/22284653/59229422-5f3b5000-8ba8-11e9-84c0-7faef0719594.png)

**Comment by Tyrrrz** [comment] 2019-06-11 18:44
Duplicate of #21

**Closed as completed** 2019-06-11 20:02 UTC
Labels: duplicate

**Comment by xamarin-enthusiast** [comment] 2019-06-12 13:18
@Tyrrrz  Is this bug crashing the same way as "App crashes for unavailable videos" #21  ?
