### ISSUE TITLE
VirusTotal (MaxSecure) claims Trojan.Malware.300983.susgen

### ISSUE THREAD

**Issue by naxey** [Tyrrrz/YoutubeDownloader#313] opened 2023-01-20 14:22 UTC
### Version

1.9.7

### Details

https://www.virustotal.com/gui/file/2175f203171a3299b1ab0a9ea56c461d48028f73f5be2e90e27d5085cbca6443
The Website VirusTotal claims it found Trojan.Malware.300983.susgen

### Steps to reproduce

Go to https://www.virustotal.com/
Upload the latest (1.9.7) zip
wait for results
inspect via graphtool for more info

**Comment by Tyrrrz** [comment] 2023-01-20 22:05
That's unfortunate.

Duplicate of #309 #297 #242 #50

**Closed as completed by Tyrrrz** 2023-01-20 22:05 UTC
Labels: duplicate
