### ISSUE TITLE
The best quality options is missing

### ISSUE THREAD

**Issue by dmhai** [Tyrrrz/YoutubeDownloader#201] opened 2021-04-21 20:42 UTC
https://www.youtube.com/watch?v=PBtQMIDNLmU
1.This video supports 1080p. But the format selection list does not have 1080p.

2. When downloading playlist ，how to down the subtitle ？

**Comment by Tyrrrz** [comment] 2021-04-22 12:25
Duplicate of #190

**Closed as completed by Tyrrrz** 2021-04-22 12:25 UTC
Labels: duplicate
