### ISSUE TITLE
Failed error on downloading videos MP3s and playlists

### ISSUE THREAD

**Issue by calvingalabuzi** [Tyrrrz/YoutubeDownloader#518] opened 2024-09-26 15:06 UTC
### Version

1.13.2

### Platform

Windows 11

### Steps to reproduce

All URLs are giving the error

### Details

Failed for all Videos i am trying 

### Checklist

- [X] I have looked through existing issues to make sure that this bug has not been reported before
- [X] I have provided a descriptive title for this issue
- [X] I have made sure that this bug is reproducible on the latest version of the application
- [X] I have provided all the information needed to reproduce this bug as efficiently as possible
- [ ] I have sponsored this project
- [ ] I have not read any of the above and just checked all the boxes to submit the issue

**Comment by v100evBG** [comment] 2024-09-26 15:26
It doesn't work for me too

**Comment by knhkse** [comment] 2024-09-27 01:46
Also for me..

**Comment by edoardoCame** [comment] 2024-09-27 16:17
same for me...

**Comment by montypx** [comment] 2024-09-27 16:54
also for me

**Comment by Tyrrrz** [comment] 2024-09-27 16:59
Duplicate of #513

**Closed as completed by Tyrrrz** 2024-09-27 16:59 UTC
Labels: duplicate
