### ISSUE TITLE
Not work this version https://github.com/Tyrrrz/YoutubeDownloader/releases/tag/1.7.16

### ISSUE THREAD

**Issue by motacano** [Tyrrrz/YoutubeDownloader#189] opened 2021-03-06 18:05 UTC
not download

playlist, etc

https://www.youtube.com/watch?v=sqDsyaqpEWk&list=PLI2XMk6t9vOtGXS32ZscrCXmMLXjCjepo

**Comment by Tyrrrz** [comment] 2021-03-07 02:38
Duplicate of #182

**Closed as completed by Tyrrrz** 2021-03-07 02:38 UTC
Labels: duplicate
