### ISSUE TITLE
Add the size of video

### ISSUE THREAD

**Issue by A-bahattab** [Tyrrrz/YoutubeDownloader#68] opened 2019-11-01 02:36 UTC
need to let the user know the size of the video will be downloaded. when the user chose 720p or 480 how much the size of each kind? i hope that this is the right place to implements some kind of problems. thanks

**Comment by Tyrrrz** [comment] 2019-11-01 08:49
Unfortunately the size is not known beforehand because the video is muxed from two separate streams. It can only be estimated.

**Comment by Tyrrrz** [comment] 2019-11-03 20:57
Related/duplicate of #34

**Closed as completed by Tyrrrz** 2019-11-03 20:57 UTC
Labels: duplicate
