### ISSUE TITLE
Add button to pause and restart download from same progress

### ISSUE THREAD

**Issue by AkshayPratapSingh09** [Tyrrrz/YoutubeDownloader#536] opened 2024-10-31 18:41 UTC
### Version

v1.13.3

### Platform

Windows 11

### Details

- Feels the requirement of a button to **Pause** and **Restart** of a downloading video, it is a very much needed function
- It is very important for people with Unstable or Limited Internet  

### Checklist

- [X] I have looked through existing issues to make sure that this bug has not been reported before
- [X] I have provided a descriptive title for this issue
- [X] I have made sure that this bug is reproducible on the latest version of the application
- [X] I have provided all the information needed to reproduce this bug as efficiently as possible
- [ ] I have sponsored this project
- [ ] I have not read any of the above and just checked all the boxes to submit the issue

**Comment by Tyrrrz** [comment] 2024-11-05 20:16
Duplicate of #107 #126

**Closed as completed by Tyrrrz** 2024-11-05 20:16 UTC
Labels: duplicate
