### ISSUE TITLE
I tried downloading a video but got 403 forbidden

### ISSUE THREAD

**Issue by 12345xinkai** [Tyrrrz/YoutubeDownloader#427] opened 2024-04-04 03:54 UTC
### Version

1.10.10

### Platform

win10

### Steps to reproduce

https://www.youtube.com/watch?v=K5qh09Hy15I, it is 20g

### Details

Expected behavior: Done
Actual: Failed

### Checklist

- [X] I have looked through existing issues to make sure that this bug has not been reported before
- [X] I have provided a descriptive title for this issue
- [X] I have made sure that this bug is reproducible on the latest version of the application
- [X] I have provided all the information needed to reproduce this bug as efficiently as possible
- [ ] I have sponsored this project

**Comment by Tyrrrz** [comment] 2024-04-04 13:17
Can you copy the error (click on the `Failed` message)

**Comment by 12345xinkai** [comment] 2024-04-04 14:45
Sorry I think this was a conversion error

**Comment by 12345xinkai** [comment] 2024-04-17 09:12
`System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (Forbidden).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at System.Net.Http.HttpClient.GetStreamAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at YoutubeExplode.Videos.Streams.MediaStream.ResolveSegmentAsync(CancellationToken cancellationToken) in /_/YoutubeExplode/Videos/Streams/MediaStream.cs:line 54
   at YoutubeExplode.Videos.Streams.MediaStream.InitializeAsync(CancellationToken cancellationToken) in /_/YoutubeExplode/Videos/Streams/MediaStream.cs:line 60
   at YoutubeExplode.Videos.Streams.StreamClient.GetAsync(IStreamInfo streamInfo, CancellationToken cancellationToken) in /_/YoutubeExplode/Videos/Streams/StreamClient.cs:line 335
   at YoutubeExplode.Videos.Streams.StreamClient.CopyToAsync(IStreamInfo streamInfo, Stream destination, IProgress`1 progress, CancellationToken cancellationToken) in /_/YoutubeExplode/Videos/Streams/StreamClient.cs:line 350
   at YoutubeExplode.Videos.Streams.StreamClient.DownloadAsync(IStreamInfo streamInfo, String filePath, IProgress`1 progress, CancellationToken cancellationToken) in /_/YoutubeExplode/Videos/Streams/StreamClient.cs:line 365
   at YoutubeExplode.Converter.Converter.PopulateStreamInputsAsync(String baseFilePath, IReadOnlyList`1 streamInfos, ICollection`1 streamInputs, IProgress`1 progress, CancellationToken cancellationToken) in /_/YoutubeExplode.Converter/Converter.cs:line 196
   at YoutubeExplode.Converter.Converter.ProcessAsync(String filePath, Container container, IReadOnlyList`1 streamInfos, IReadOnlyList`1 closedCaptionTrackInfos, IProgress`1 progress, CancellationToken cancellationToken) in /_/YoutubeExplode.Converter/Converter.cs:line 271
   at YoutubeExplode.Converter.ConversionExtensions.DownloadAsync(VideoClient videoClient, IReadOnlyList`1 streamInfos, IReadOnlyList`1 closedCaptionTrackInfos, ConversionRequest request, IProgress`1 progress, CancellationToken cancellationToken) in /_/YoutubeExplode.Converter/ConversionExtensions.cs:line 85
   at YoutubeDownloader.Core.Downloading.VideoDownloader.DownloadVideoAsync(String filePath, IVideo video, VideoDownloadOption downloadOption, Boolean includeSubtitles, IProgress`1 progress, CancellationToken cancellationToken) in D:\a\YoutubeDownloader\YoutubeDownloader\YoutubeDownloader.Core\Downloading\VideoDownloader.cs:line 67
   at YoutubeDownloader.ViewModels.Components.DashboardViewModel.<>c__DisplayClass30_0.<<EnqueueDownload>b__0>d.MoveNext() in D:\a\YoutubeDownloader\YoutubeDownloader\YoutubeDownloader\ViewModels\Components\DashboardViewModel.cs:line 100`

**Comment by anuragtyagi-dev** [comment] 2024-06-11 11:12
Does this resolved for you now ? 


> `System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (Forbidden). at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode() at System.Net.Http.HttpClient.GetStreamAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken) at YoutubeExplode.Videos.Streams.MediaStream.ResolveSegmentAsync(CancellationToken cancellationToken) in /_/YoutubeExplode/Videos/Streams/MediaStream.cs:line 54 at YoutubeExplode.Videos.Streams.MediaStream.InitializeAsync(CancellationToken cancellationToken) in /_/YoutubeExplode/Videos/Streams/MediaStream.cs:line 60 at YoutubeExplode.Videos.Streams.StreamClient.GetAsync(IStreamInfo streamInfo, CancellationToken cancellationToken) in /_/YoutubeExplode/Videos/Streams/StreamClient.cs:line 335 at YoutubeExplode.Videos.Streams.StreamClient.CopyToAsync(IStreamInfo streamInfo, Stream destination, IProgress`1 progress, CancellationToken cancellationToken) in /_/YoutubeExplode/Videos/Streams/StreamClient.cs:line 350 at YoutubeExplode.Videos.Streams.StreamClient.DownloadAsync(IStreamInfo streamInfo, String filePath, IProgress`1 progress, CancellationToken cancellationToken) in /_/YoutubeExplode/Videos/Streams/StreamClient.cs:line 365 at YoutubeExplode.Converter.Converter.PopulateStreamInputsAsync(String baseFilePath, IReadOnlyList`1 streamInfos, ICollection`1 streamInputs, IProgress`1 progress, CancellationToken cancellationToken) in /_/YoutubeExplode.Converter/Converter.cs:line 196 at YoutubeExplode.Converter.Converter.ProcessAsync(String filePath, Container container, IReadOnlyList`1 streamInfos, IReadOnlyList`1 closedCaptionTrackInfos, IProgress`1 progress, CancellationToken cancellationToken) in /_/YoutubeExplode.Converter/Converter.cs:line 271 at YoutubeExplode.Converter.ConversionExtensions.DownloadAsync(VideoClient videoClient, IReadOnlyList`1 streamInfos, IReadOnlyList`1 closedCaptionTrackInfos, ConversionRequest request, IProgress`1 progress, CancellationToken cancellationToken) in /_/YoutubeExplode.Converter/ConversionExtensions.cs:line 85 at YoutubeDownloader.Core.Downloading.VideoDownloader.DownloadVideoAsync(String filePath, IVideo video, VideoDownloadOption downloadOption, Boolean includeSubtitles, IProgress`1 progress, CancellationToken cancellationToken) in D:\a\YoutubeDownloader\YoutubeDownloader\YoutubeDownloader.Core\Downloading\VideoDownloader.cs:line 67 at YoutubeDownloader.ViewModels.Components.DashboardViewModel.<>c__DisplayClass30_0.<<EnqueueDownload>b__0>d.MoveNext() in D:\a\YoutubeDownloader\YoutubeDownloader\YoutubeDownloader\ViewModels\Components\DashboardViewModel.cs:line 100`

**Comment by Tyrrrz** [comment] 2024-08-07 00:02
Not sure, 403/401 errors are very hard to track down.

**Comment by Tyrrrz** [comment] 2024-08-07 00:42
This issue is essentially a duplicate of #469 (also a 403 error), so closing for organizational purposes

**Closed by Tyrrrz** 2024-08-07 00:42 UTC
Labels: bug, duplicate
