### ISSUE TITLE
Downloading playlists is not working

### ISSUE THREAD

**Issue by NeDDy3z** [Tyrrrz/YoutubeDownloader#185] opened 2021-02-22 21:16 UTC
I can download single videos but downloading playlists is broken.

![Snímek obrazovky 2021-02-22 221422](https://user-images.githubusercontent.com/79312101/108771101-74facf80-755b-11eb-8104-0255ab7ec705.png)

**Comment by Tyrrrz** [comment] 2021-02-23 02:57
Duplicate of #182

**Closed as completed by Tyrrrz** 2021-02-23 02:57 UTC
Labels: duplicate
