### ISSUE TITLE
Download error

### ISSUE THREAD

**Issue by Lapius7** [Tyrrrz/YoutubeDownloader#481] opened 2024-08-08 17:09 UTC
### Version

maybe v1.12.2

### Platform

Windows 11

### Steps to reproduce

一部の動画URLを入力するとエラーになってしまい、動画がダウンロードされません。
![スクリーンショット 2024-08-09 020329](https://github.com/user-attachments/assets/7b2d21de-0b74-49c6-b3bb-cdd31f555037)

### Details

ダウンロードされてほしい。

### Checklist

- [X] I have looked through existing issues to make sure that this bug has not been reported before
- [X] I have provided a descriptive title for this issue
- [X] I have made sure that this bug is reproducible on the latest version of the application
- [X] I have provided all the information needed to reproduce this bug as efficiently as possible
- [X] I have sponsored this project
- [ ] I have not read any of the above and just checked all the boxes to submit the issue

**Comment by Tyrrrz** [comment] 2024-08-09 02:18
Duplicate of #469 (also 403 error).

**Closed as completed by Tyrrrz** 2024-08-09 02:18 UTC
Labels: duplicate
