### ISSUE TITLE
Unable to download this video - Status Failed and ZERO byte file created

### ISSUE THREAD

**Issue by xamarin-enthusiast** [Tyrrrz/YoutubeDownloader#42] opened 2019-07-09 14:32 UTC
Do a search for "deep relaxing music" then try to download it. 

Status shows **Failed**.

And a ZERO byte file is created.  If download fails, please don't leave behind a ZERO byte file.

![image](https://user-images.githubusercontent.com/22284653/60896443-5afc6400-a234-11e9-9a2d-9ee65792df55.png)

![image](https://user-images.githubusercontent.com/22284653/60896735-d3632500-a234-11e9-9a96-3dd7637a0033.png)

**Comment by Tyrrrz** [comment] 2019-07-10 12:57
Duplicate of #41

**Closed as completed by Tyrrrz** 2019-07-10 12:57 UTC
Labels: duplicate
