### ISSUE TITLE
Failed download for all playlist or video

### ISSUE THREAD

**Issue by mohseenjamall** [Tyrrrz/YoutubeDownloader#517] opened 2024-09-26 09:28 UTC
### Version

v1.13.2

### Platform

Windows 11

### Steps to reproduce

step1: https://www.youtube.com/playlist?list=PL6NcFPy4N0FLrDQDjfo9q4xepI2yJPXNz
step2: choose the download folder
step3: download
step4: ![image](https://github.com/user-attachments/assets/09bf583c-fafd-47a9-984b-38de10adc43d)

### Details

When I download any Playlist or Video, the results failed 

### Checklist

- [X] I have looked through existing issues to make sure that this bug has not been reported before
- [X] I have provided a descriptive title for this issue
- [X] I have made sure that this bug is reproducible on the latest version of the application
- [X] I have provided all the information needed to reproduce this bug as efficiently as possible
- [ ] I have sponsored this project
- [ ] I have not read any of the above and just checked all the boxes to submit the issue

**Comment by elef88** [comment] 2024-09-26 11:52
This is the same error as #513, it just doesn't show the error pop up when you download a playlist

**Comment by zjjohncq** [comment] 2024-09-26 12:34
Same issue. but there is one more thing not working for me as V1.13.2
when I enter something for search, it always response as "playlist {searchkey} is not available"
![image](https://github.com/user-attachments/assets/a07750a6-e462-416e-8ee4-2ca214ccf798)

**Comment by NikoTumi** [comment] 2024-09-26 12:36
![Screenshot 2024-08-13 175850](https://github.com/user-attachments/assets/1708d655-5d92-4b04-9551-da365cc34b0f)

**Comment by NikoTumi** [comment] 2024-09-26 12:36
![image](https://github.com/user-attachments/assets/55b180e0-4740-43db-afcd-953502a27111)

**Comment by NikoTumi** [comment] 2024-09-26 12:46
![image](https://github.com/user-attachments/assets/1b984b6f-38e1-4c45-a5b4-026ae9ab8729)

**Comment by ealvesss** [comment] 2024-09-26 14:47
Looks like the issue should be solved  in [YouTubeExplode Lib](https://github.com/Tyrrrz/YoutubeExplode/issues/817)

**Comment by ealvesss** [comment] 2024-09-26 14:48
duplicated bug as #516

**Comment by Tyrrrz** [comment] 2024-09-27 16:59
Duplicate of #513

**Closed as completed by Tyrrrz** 2024-09-27 16:59 UTC
Labels: duplicate
