### ISSUE TITLE
Downloads not working

### ISSUE THREAD

**Issue by LetsPlayNintendoITA2023** [Tyrrrz/YoutubeDownloader#423] opened 2024-03-22 20:31 UTC
### Version

1.10.11

### Platform

Windows 10

### Steps to reproduce

Try to download any video

### Details

Expected: It starts downloading
What happens: ![immagine](https://github.com/Tyrrrz/YoutubeDownloader/assets/137847553/b1c5eeae-443a-4b15-8443-31ce89c42608)

### Checklist

- [X] I have looked through existing issues to make sure that this bug has not been reported before
- [X] I have provided a descriptive title for this issue
- [X] I have made sure that this bug is reproducible on the latest version of the application
- [X] I have provided all the information needed to reproduce this bug as efficiently as possible
- [ ] I have sponsored this project

**Comment by DurradonXylles** [comment] 2024-03-23 04:40
Yeah, I'm getting similar errors whenever I try to download videos as well. I think it might have to do with changes to the YouTube backend that Google implemented in the last month, since a lot of other YT related stuff has broken and required an update in that time.

**Comment by DurradonXylles** [comment] 2024-03-23 19:42
Update: I found that I get this error when I'm logged into my account via the downloader, Any non-restricted video will let me download them if I log off, but if I log back in I get this error again. I either get this error or the one above:
![image](https://github.com/Tyrrrz/YoutubeDownloader/assets/56055805/1cefc981-3c5e-4c1d-94d8-b83894fdd6db)

Worst of all, it's inconsistent. I have been able to get videos to work sometimes if I restart the app, but only sometimes. It's weird.

**Comment by Tyrrrz** [comment] 2024-03-23 23:42
Copy-paste the URL of the video you're downloading.

**Comment by DurradonXylles** [comment] 2024-03-24 13:07
Hey, so I tested out a number of videos since I posted that comment, and they all seem to work for me now. The one I was trying to download above was a short video from my feed, chosen as an example because it was short: https://www.youtube.com/watch?v=oqnZcu3eAOY

I can't speak on the person who originally opened the issue though.

**Comment by LetsPlayNintendoITA2023** [comment] 2024-03-26 19:19
yea seems like logging out helps

**Comment by vtbinsulator** [comment] 2024-04-01 04:42
I have the same problem,and after log out problem isnt solved.

**Comment by apikidy** [comment] 2024-07-14 07:53
i have problem, ..

![Screenshot_3](https://github.com/user-attachments/assets/83995c47-bf67-4f6d-9c45-f95cdd47fa6e)

**Comment by Tyrrrz** [comment] 2024-08-06 23:42
It looks like it was a transient issue that cannot be reproduced anymore. Unfortunately, such situations happen often with YouTube and they are hard to debug. Closing the issue.

**Closed as completed by Tyrrrz** 2024-08-06 23:42 UTC
Labels: bug

**Comment by LetsPlayNintendoITA2023** [comment] 2024-09-16 21:05
video watch page broken. guess it got blocked again
