### ISSUE TITLE
"Failed" Status

### ISSUE THREAD

**Issue by ClostroOffi** [Tyrrrz/YoutubeDownloader#334] opened 2023-04-30 09:48 UTC
### Version

1.9.10

### Details

I tried restarting the app, the computer, the download, nothin' changed.

![image](https://user-images.githubusercontent.com/81104065/235346661-f1d35161-c861-415a-bf12-ed631d98b601.png)

### Steps to reproduce

-Download the video

**Comment by Tyrrrz** [comment] 2023-04-30 13:18
Duplicate of #333

**Closed by Tyrrrz** 2023-04-30 13:18 UTC
Labels: duplicate
