### ISSUE TITLE
Video [video_id] is unavailable

### ISSUE THREAD

**Issue by mrnams** [Tyrrrz/YoutubeDownloader#51] opened 2019-07-30 07:16 UTC
Version:1.5.5
Not able to download mp3, it display below error

Video [video_id] is unavailable

e.g.
https://youtu.be/PqnEdcxu0-I

**Comment by Tyrrrz** [comment] 2019-07-30 10:19
Duplicate of #49

**Closed as completed by Tyrrrz** 2019-07-30 10:19 UTC
Labels: duplicate
