### ISSUE TITLE
Add username and password to URL?

### ISSUE THREAD

**Issue by NeilMJohnson** [Tyrrrz/YoutubeDownloader#95] opened 2020-03-31 07:07 UTC
I have been getting the occasional 403 error for restricted content that I can view in YouTube when I am logged into my account.  It would be useful to be able to log a username and password for your YouTube Account and use it when you get 403 errors.

**Comment by Tyrrrz** [comment] 2020-04-12 20:39
Hi.
This is actually caused by another issue.
Duplicate of #89.

**Closed as completed by Tyrrrz** 2020-04-12 20:39 UTC
Labels: duplicate
